name: Deploy

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish-image.yml
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - run: echo Deply
