name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Cargo.toml
        run: |
          tag=${{ steps.release_drafter.outputs.tag_name }}
          sed -i "s/^version = \".*\"/version = \"${tag#v}\"/" Cargo.toml
        continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version

